<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LIN33004137"><DocLocation><![CDATA[C:\framework\QTP-Hybrid-Framework\QTP-Hybrid-Framework\TestCases\orangehrm_11]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[orangehrm_11]]></DName>
<Res><![CDATA[Res24]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:41]]></Time>
<TimeTick>1676361401</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:41]]></Time>
<TimeTick>1676361401</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:42]]></Time>
<TimeTick>1676361402</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[Login]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:42]]></Time>
<TimeTick>1676361402</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:42]]></Time>
<TimeTick>1676361402</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:42]]></Time>
<TimeTick>1676361402</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63eb2d5da7b3959dae3c5969ba13413df5b4cf4a242b"]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:42]]></Time>
<TimeTick>1676361402</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:42]]></Time>
<TimeTick>1676361402</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="15" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 13:26:42" eTime="14-02-2023 - 13:26:42" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="12" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[pim]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:44]]></Time>
<TimeTick>1676361404</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_5]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:44]]></Time>
<TimeTick>1676361404</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:44]]></Time>
<TimeTick>1676361404</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="pim" SourceLine="1" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="30" Source="pim" SourceLine="1" >
<Disp><![CDATA[OrangeHRM_5]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:46]]></Time>
<TimeTick>1676361406</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Type for hints....Set]]></Obj>
<Details plainTxt="False" ><![CDATA["bhargavi"]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:46]]></Time>
<TimeTick>1676361406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" Source="pim" SourceLine="2" >
<Disp><![CDATA[Type for hints....Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:46]]></Time>
<TimeTick>1676361406</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="41" Source="pim" SourceLine="3" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Type for hints....Set]]></Obj>
<Details plainTxt="False" ><![CDATA["madhu"]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:46]]></Time>
<TimeTick>1676361406</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="44" Source="pim" SourceLine="4" >
<Disp><![CDATA[Type for hints....Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Employee InformationEmployee.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:46]]></Time>
<TimeTick>1676361406</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="47" Source="pim" SourceLine="5" >
<Disp><![CDATA[Employee InformationEmployee.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:46]]></Time>
<TimeTick>1676361406</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="50" Source="pim" SourceLine="6" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Add.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:47]]></Time>
<TimeTick>1676361407</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="53" Source="pim" SourceLine="7" >
<Disp><![CDATA[Add.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="37" Source="pim" SourceLine="2" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:48]]></Time>
<TimeTick>1676361408</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["madhu"]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:48]]></Time>
<TimeTick>1676361408</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="57" Source="pim" SourceLine="8" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["mamidela"]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:48]]></Time>
<TimeTick>1676361408</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="60" Source="pim" SourceLine="9" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["039588"]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:48]]></Time>
<TimeTick>1676361408</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="63" Source="pim" SourceLine="10" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:48]]></Time>
<TimeTick>1676361408</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="66" Source="pim" SourceLine="11" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="56" Source="pim" SourceLine="8" >
<Disp><![CDATA[OrangeHRM_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_8]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:48]]></Time>
<TimeTick>1676361408</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:48]]></Time>
<TimeTick>1676361408</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="70" Source="pim" SourceLine="12" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Save_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:48]]></Time>
<TimeTick>1676361408</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="73" Source="pim" SourceLine="13" >
<Disp><![CDATA[Save_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:48]]></Time>
<TimeTick>1676361408</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="76" Source="pim" SourceLine="14" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="69" Source="pim" SourceLine="12" >
<Disp><![CDATA[OrangeHRM_8]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:51]]></Time>
<TimeTick>1676361411</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Type for hints....Set]]></Obj>
<Details plainTxt="False" ><![CDATA["madhu"]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:51]]></Time>
<TimeTick>1676361411</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="81" Source="pim" SourceLine="15" >
<Disp><![CDATA[Type for hints....Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:51]]></Time>
<TimeTick>1676361411</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="84" Source="pim" SourceLine="16" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[WebCheckBox.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[14-02-2023 - 13:26:52]]></Time>
<TimeTick>1676361412</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="88" Source="pim" SourceLine="17" >
<Disp><![CDATA[WebCheckBox.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Delete Selected]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Delete&nbsp;Selected"&nbsp;(of&nbsp;class&nbsp;WebButton).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 13:27:12]]></Time>
<TimeTick>1676361432</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Delete Selected]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebButton<br>Html Tag = BUTTON<br>_xpath = //DIV/DIV/DIV/BUTTON[normalize-space()="Delete Selected"]<br>|Visible = -1<br>Value = Delete Selected<br>Type = button<br>Name = Delete Selected<br>Html Id = <br>DHTML Class = oxd-button oxd-button--medium oxd-button--label-danger orangehrm-horizontal-margin<br>acc_name = <br>]]></Details>
<Time><![CDATA[14-02-2023 - 13:27:12]]></Time>
<TimeTick>1676361432</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="133" status="Warning" nType="Description" Source="pim" SourceLine="18" >
<Disp><![CDATA[Delete Selected]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="132" status="Failed" nType="Run Error" Source="pim" SourceLine="18" >
<Disp><![CDATA[Delete Selected]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="80" status="Failed" Source="pim" SourceLine="15" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="29" status="Failed" Source="pim" SourceLine="1" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 13:27:12]]></Time>
<TimeTick>1676361432</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Delete Selected&quot; (of class WebButton).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (19): &quot;Browser(&quot;OrangeHRM&quot;).Page(&quot;OrangeHRM_2&quot;).WebButton(&quot;Delete Selected&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[14-02-2023 - 13:27:12]]></Time>
<TimeTick>1676361432</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="135" status="Failed" Source="pim" SourceLine="18" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[14-02-2023 - 13:27:14]]></Time>
<TimeTick>1676361434</TimeTick>
<NodeArgs eType="General" icon="13" nRep="136" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="134" status="Failed" Source="pim" SourceLine="18" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 13:26:42" eTime="14-02-2023 - 13:27:14" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="25" status="Failed" >
<Disp><![CDATA[pim Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[orangehrm_11 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="14-02-2023 - 13:26:40" eTime="14-02-2023 - 13:27:14" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test orangehrm_11 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>